# Generated by Django 3.1.2 on 2020-10-18 01:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='contatos',
            field=models.ManyToManyField(blank=True, related_name='_usuario_contatos_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
