# Generated by Django 3.1.2 on 2020-10-18 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201018_0146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='contatos',
        ),
    ]
