# Generated by Django 3.1.2 on 2020-10-18 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_usuario_contatos'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='contatos',
            field=models.ManyToManyField(blank=True, null=True, to='api.Contato'),
        ),
    ]
