# Generated by Django 3.1.2 on 2021-01-11 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_usuario_contatos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='endereço',
            new_name='endereco',
        ),
    ]
